package gov.pr.celepar.abi.pojo;

// Generated 24/12/2009 11:14:35 by Hibernate Tools 3.2.0.CR1
import java.math.BigDecimal;
import java.util.Date;


/**
 * Avaliacao generated by hbm2java
 */
public class Avaliacao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4021971070216362327L;
	private Integer codAvaliacao;
    private Edificacao edificacao;
    private BemImovel bemImovel;
    private BigDecimal valor;
    private Date dataAvaliacao;
    private Date tsInclusao;
    private Date tsAtualizacao;
    private String cpfResponsavel;
    private Integer indTipoAvaliacao;

    public Avaliacao() {
    }

    public Avaliacao(Integer codAvaliacao, Edificacao edificacao,
        BemImovel bemImovel, BigDecimal valor, Date dataAvaliacao,
        Date tsInclusao, Date tsAtualizacao, String cpfResponsavel) {
        this.codAvaliacao = codAvaliacao;
        this.edificacao = edificacao;
        this.bemImovel = bemImovel;
        this.valor = valor;
        this.dataAvaliacao = dataAvaliacao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
    }

    public Integer getCodAvaliacao() {
        return this.codAvaliacao;
    }

    public void setCodAvaliacao(Integer codAvaliacao) {
        this.codAvaliacao = codAvaliacao;
    }

    public Edificacao getEdificacao() {
        return this.edificacao;
    }

    public void setEdificacao(Edificacao edificacao) {
        this.edificacao = edificacao;
    }

    public BemImovel getBemImovel() {
        return this.bemImovel;
    }

    public void setBemImovel(BemImovel bemImovel) {
        this.bemImovel = bemImovel;
    }

    public BigDecimal getValor() {
        return this.valor;
    }

    public void setValor(BigDecimal valor) {
        this.valor = valor;
    }

    public Date getDataAvaliacao() {
        return this.dataAvaliacao;
    }

    public void setDataAvaliacao(Date dataAvaliacao) {
        this.dataAvaliacao = dataAvaliacao;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

  

    public Integer getIndTipoAvaliacao() {
		return indTipoAvaliacao;
	}

	public void setIndTipoAvaliacao(Integer indTipoAvaliacao) {
		this.indTipoAvaliacao = indTipoAvaliacao;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Avaliacao other = (Avaliacao) obj;
		if (codAvaliacao == null) {
			if (other.codAvaliacao != null)
				return false;
		} else if (!codAvaliacao.equals(other.codAvaliacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codAvaliacao == null) ? 0 : codAvaliacao.hashCode());
		return result;
	}
}
