package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * ClassificacaoBemImovel generated by hbm2java
 */
public class ClassificacaoBemImovel implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4387778686202567864L;
	private Integer codClassificacaoBemImovel;
    private String descricao;
    private Set<BemImovel> bemImovels = new HashSet<BemImovel>(0);

    public ClassificacaoBemImovel() {
    }

    public ClassificacaoBemImovel(Integer codClassificacaoBemImovel,
        String descricao) {
        this.codClassificacaoBemImovel = codClassificacaoBemImovel;
        this.descricao = descricao;
    }

    public ClassificacaoBemImovel(Integer codClassificacaoBemImovel,
        String descricao, Set<BemImovel> bemImovels) {
        this.codClassificacaoBemImovel = codClassificacaoBemImovel;
        this.descricao = descricao;
        this.bemImovels = bemImovels;
    }

    public Integer getCodClassificacaoBemImovel() {
        return this.codClassificacaoBemImovel;
    }

    public void setCodClassificacaoBemImovel(Integer codClassificacaoBemImovel) {
        this.codClassificacaoBemImovel = codClassificacaoBemImovel;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<BemImovel> getBemImovels() {
        return this.bemImovels;
    }

    public void setBemImovels(Set<BemImovel> bemImovels) {
        this.bemImovels = bemImovels;
    }

   

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		ClassificacaoBemImovel other = (ClassificacaoBemImovel) obj;
		if (codClassificacaoBemImovel == null) {
			if (other.codClassificacaoBemImovel != null)
				return false;
		} else if (!codClassificacaoBemImovel
				.equals(other.codClassificacaoBemImovel))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codClassificacaoBemImovel == null) ? 0
						: codClassificacaoBemImovel.hashCode());
		return result;
	}
}
