package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * DenominacaoImovel generated by hbm2java
 */
public class DenominacaoImovel implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4922190800809945909L;
	private Integer codDenominacaoImovel;
    private String descricao;
    private Set<BemImovel> bemImovels = new HashSet<BemImovel>(0);
    private Set<ParametroVistoriaDenominacaoImovel> listaParametroVistoriaDenominacaoImovel = new HashSet<ParametroVistoriaDenominacaoImovel>(0);

    public DenominacaoImovel() {
    }

    public DenominacaoImovel(Integer codDenominacaoImovel, String descricao) {
        this.codDenominacaoImovel = codDenominacaoImovel;
        this.descricao = descricao;
    }

    public DenominacaoImovel(Integer codDenominacaoImovel, String descricao,
        Set<BemImovel> bemImovels) {
        this.codDenominacaoImovel = codDenominacaoImovel;
        this.descricao = descricao;
        this.bemImovels = bemImovels;
    }

    public Integer getCodDenominacaoImovel() {
        return this.codDenominacaoImovel;
    }

    public void setCodDenominacaoImovel(Integer codDenominacaoImovel) {
        this.codDenominacaoImovel = codDenominacaoImovel;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<BemImovel> getBemImovels() {
        return this.bemImovels;
    }

    public void setBemImovels(Set<BemImovel> bemImovels) {
        this.bemImovels = bemImovels;
    }

    

   

	public Set<ParametroVistoriaDenominacaoImovel> getListaParametroVistoriaDenominacaoImovel() {
		return listaParametroVistoriaDenominacaoImovel;
	}

	public void setListaParametroVistoriaDenominacaoImovel(
			Set<ParametroVistoriaDenominacaoImovel> listaParametroVistoriaDenominacaoImovel) {
		this.listaParametroVistoriaDenominacaoImovel = listaParametroVistoriaDenominacaoImovel;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		DenominacaoImovel other = (DenominacaoImovel) obj;
		if (codDenominacaoImovel == null) {
			if (other.codDenominacaoImovel != null)
				return false;
		} else if (!codDenominacaoImovel.equals(other.codDenominacaoImovel))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codDenominacaoImovel == null) ? 0 : codDenominacaoImovel
						.hashCode());
		return result;
	}
}
