package gov.pr.celepar.abi.pojo;

import gov.pr.celepar.abi.util.Dominios;
import gov.pr.celepar.abi.util.Util;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;


/**
 * Documentacao generated by hbm2java
 */
public class Documentacao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 894750743428860682L;
	private Integer codDocumentacao;
    private Edificacao edificacao;
    private BemImovel bemImovel;
    private TipoDocumentacao tipoDocumentacao;
    private Documentacao documentacao;
    private String descricao;
    private String anexo;
    private Date tsInclusao;
    private String responsavelDocumentacao;
    private String cpfResponsavel;
    private Date tsAtualizacao;
    private Cartorio cartorio;
    private Tabelionato tabelionato;
    private String numeroDocumentoCartorial;
    private String numeroDocumentoTabelional;
    private String nirf;
    private String niif;
    private String incra;
    private Set<Documentacao> documentacaos = new HashSet<Documentacao>(0);
    private Set<Notificacao> notificacaos = new HashSet<Notificacao>(0);
    private Set<OcorrenciaDocumentacao> ocorrenciaDocumentacaos = new HashSet<OcorrenciaDocumentacao>(0);
    private String descricaoAnexo;
    private Integer classificacaoImovel;
	private String detalhesRelatorio;

    public void setDetalhesRelatorio(String detalhesRelatorio) {
		this.detalhesRelatorio = detalhesRelatorio;
	}

	public Documentacao() {
    }

    public Documentacao(Integer codDocumentacao, Edificacao edificacao,
        BemImovel bemImovel, TipoDocumentacao tipoDocumentacao,
        Documentacao documentacao, String descricao, String anexo,
        Date tsInclusao, String responsavelDocumentacao,
        String cpfResponsavel, Date tsAtualizacao) {
        this.codDocumentacao = codDocumentacao;
        this.edificacao = edificacao;
        this.bemImovel = bemImovel;
        this.tipoDocumentacao = tipoDocumentacao;
        this.documentacao = documentacao;
        this.descricao = descricao;
        this.anexo = anexo;
        this.tsInclusao = tsInclusao;
        this.responsavelDocumentacao = responsavelDocumentacao;
        this.cpfResponsavel = cpfResponsavel;
        this.tsAtualizacao = tsAtualizacao;
    }

    public Documentacao(Integer codDocumentacao, Edificacao edificacao,
        BemImovel bemImovel, TipoDocumentacao tipoDocumentacao,
        Documentacao documentacao, String descricao, String anexo,
        Date tsInclusao, String responsavelDocumentacao,
        String cpfResponsavel, Date tsAtualizacao,
        Set<Documentacao> documentacaos, Set<Notificacao> notificacaos,
        Set<OcorrenciaDocumentacao> ocorrenciaDocumentacaos) {
        this.codDocumentacao = codDocumentacao;
        this.edificacao = edificacao;
        this.bemImovel = bemImovel;
        this.tipoDocumentacao = tipoDocumentacao;
        this.documentacao = documentacao;
        this.descricao = descricao;
        this.anexo = anexo;
        this.tsInclusao = tsInclusao;
        this.responsavelDocumentacao = responsavelDocumentacao;
        this.cpfResponsavel = cpfResponsavel;
        this.tsAtualizacao = tsAtualizacao;
        this.documentacaos = documentacaos;
        this.notificacaos = notificacaos;
        this.ocorrenciaDocumentacaos = ocorrenciaDocumentacaos;
    }

    
    
    public Cartorio getCartorio() {
		return cartorio;
	}

	public void setCartorio(Cartorio cartorio) {
		this.cartorio = cartorio;
	}

	public Tabelionato getTabelionato() {
		return tabelionato;
	}

	public void setTabelionato(Tabelionato tabelionato) {
		this.tabelionato = tabelionato;
	}

	public String getNumeroDocumentoCartorial() {
		return numeroDocumentoCartorial;
	}

	public void setNumeroDocumentoCartorial(String numeroDocumentoCartorial) {
		this.numeroDocumentoCartorial = numeroDocumentoCartorial;
	}

	public String getNumeroDocumentoTabelional() {
		return numeroDocumentoTabelional;
	}

	public void setNumeroDocumentoTabelional(String numeroDocumentoTabelional) {
		this.numeroDocumentoTabelional = numeroDocumentoTabelional;
	}

	public String getNirf() {
		return nirf;
	}

	public void setNirf(String nirf) {
		this.nirf = nirf;
	}

	public String getNiif() {
		return niif;
	}

	public void setNiif(String niif) {
		this.niif = niif;
	}

	public String getIncra() {
		return incra;
	}

	public void setIncra(String incra) {
		this.incra = incra;
	}

	public Integer getCodDocumentacao() {
        return this.codDocumentacao;
    }

    public void setCodDocumentacao(Integer codDocumentacao) {
        this.codDocumentacao = codDocumentacao;
    }

    public Edificacao getEdificacao() {
        return this.edificacao;
    }

    public void setEdificacao(Edificacao edificacao) {
        this.edificacao = edificacao;
    }

    public BemImovel getBemImovel() {
        return this.bemImovel;
    }

    public void setBemImovel(BemImovel bemImovel) {
        this.bemImovel = bemImovel;
    }

    public TipoDocumentacao getTipoDocumentacao() {
        return this.tipoDocumentacao;
    }

    public void setTipoDocumentacao(TipoDocumentacao tipoDocumentacao) {
        this.tipoDocumentacao = tipoDocumentacao;
    }

    public Documentacao getDocumentacao() {
        return this.documentacao;
    }

    public void setDocumentacao(Documentacao documentacao) {
        this.documentacao = documentacao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getAnexo() {
        return this.anexo;
    }

    public void setAnexo(String anexo) {
        this.anexo = anexo;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public String getResponsavelDocumentacao() {
        return this.responsavelDocumentacao;
    }

    public void setResponsavelDocumentacao(String responsavelDocumentacao) {
        this.responsavelDocumentacao = responsavelDocumentacao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public Set<Documentacao> getDocumentacaos() {
        return this.documentacaos;
    }

    public void setDocumentacaos(Set<Documentacao> documentacaos) {
        this.documentacaos = documentacaos;
    }

    public Set<Notificacao> getNotificacaos() {
        return this.notificacaos;
    }

    public void setNotificacaos(Set<Notificacao> notificacaos) {
        this.notificacaos = notificacaos;
    }

    public Set<OcorrenciaDocumentacao> getOcorrenciaDocumentacaos() {
        return this.ocorrenciaDocumentacaos;
    }

    public void setOcorrenciaDocumentacaos(
        Set<OcorrenciaDocumentacao> ocorrenciaDocumentacaos) {
        this.ocorrenciaDocumentacaos = ocorrenciaDocumentacaos;
    }
    
    @Transient
    public String getDetalhesRelatorio() {
		StringBuffer aux = new StringBuffer();
		if (getCartorio()!=null && !Util.strEmBranco(getCartorio().getDescricao())){
			aux.append("Cartório: ").append(getCartorio().getDescricao()).append("\n");
			
		}
		if(!Util.strEmBranco(getNumeroDocumentoCartorial())){
			aux.append("Número Documento Cartorial: ").append(getNumeroDocumentoCartorial()).append("\n");
		}
		if (this.classificacaoImovel != null && this.classificacaoImovel.equals(Dominios.classificacaoImovel.CLASSIFICACAO_RURAL.getIndex())){
			if (!Util.strEmBranco(nirf)){
				aux.append("Nirf: ").append(getNirf()).append("\n");
			}
			if (!Util.strEmBranco(incra)){
				aux.append("Incra: ").append(getIncra()).append("\n");
			}
		}else{
			if (!Util.strEmBranco(niif)){
				aux.append("Niif: ").append(getNiif()).append("\n");
			}
		}
		if ( getTabelionato()!=null && !Util.strEmBranco(getTabelionato().getDescricao())){
			aux.append("Tabelionato: ").append(getTabelionato().getDescricao()).append("\n");
			
		}
		if(!Util.strEmBranco(getNumeroDocumentoTabelional())){
			aux.append("Número Documento Tabelional: ").append(getNumeroDocumentoTabelional());
		}
		this.detalhesRelatorio= aux.toString();
		return detalhesRelatorio;
	}	

   

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Documentacao other = (Documentacao) obj;
		if (codDocumentacao == null) {
			if (other.codDocumentacao != null)
				return false;
		} else if (!codDocumentacao.equals(other.codDocumentacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codDocumentacao == null) ? 0 : codDocumentacao.hashCode());
		return result;
	}

	public void setClassificacaoImovel(Integer classificacaoImovel) {
		this.classificacaoImovel = classificacaoImovel;
	}

	@Transient
	public Integer getClassificacaoImovel() {
		return classificacaoImovel;
	}

	public void setDescricaoAnexo(String descricaoAnexo) {
		this.descricaoAnexo = descricaoAnexo;
	}

	public String getDescricaoAnexo() {
		return descricaoAnexo;
	}
}
