package gov.pr.celepar.abi.pojo;

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Edificacao generated by hbm2java
 */
public class Edificacao implements java.io.Serializable {
	
	
    
	private static final long serialVersionUID = -2536331166185132991L;
	private Integer codEdificacao;
    private TipoEdificacao tipoEdificacao;
    private TipoConstrucao tipoConstrucao;
    private BemImovel bemImovel;
    private String especificacao;
    private String logradouro;
    private BigDecimal areaConstruida;
    private BigDecimal areaUtilizada;
    private Date dataAverbacao;
    private Date tsInclusao;
    private Date tsAtualizacao;
    private String cpfResponsavel;
    private Set<Documentacao> documentacaos = new HashSet<Documentacao>(0);
    private Set<Lote> lotes = new HashSet<Lote>(0);
    private Set<Avaliacao> avaliacaos = new HashSet<Avaliacao>(0);
    private Set<Ocupacao> ocupacaos = new HashSet<Ocupacao>(0);
    private Set<Vistoria> listaVistoria = new HashSet<Vistoria>(0);
    private Set<ItemDoacao> listaItemDoacao = new HashSet<ItemDoacao>(0);
    private Set<ItemTransferencia> listaItemTransferencia = new HashSet<ItemTransferencia>(0);

    public Edificacao() {
    }

    public Edificacao(Integer codEdificacao, TipoEdificacao tipoEdificacao,
    	TipoConstrucao tipoConstrucao,
        BemImovel bemImovel, String especificacao, String logradouro,
        BigDecimal areaConstruida, BigDecimal areaUtilizada,
        Date tsInclusao, Date tsAtualizacao, String cpfResponsavel) {
        this.codEdificacao = codEdificacao;
        this.tipoEdificacao = tipoEdificacao;
        this.tipoConstrucao = tipoConstrucao;
        this.bemImovel = bemImovel;
        this.especificacao = especificacao;
        this.logradouro = logradouro;
        this.areaConstruida = areaConstruida;
        this.areaUtilizada = areaUtilizada;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
    }

    public Edificacao(Integer codEdificacao, TipoEdificacao tipoEdificacao,
    	TipoConstrucao tipoConstrucao,
        BemImovel bemImovel, String especificacao, String logradouro,
        BigDecimal areaConstruida, BigDecimal areaUtilizada,
        Date dataAverbacao, Date tsInclusao, Date tsAtualizacao,
        String cpfResponsavel, Set<Documentacao> documentacaos,
        Set<Lote> lotes, Set<Avaliacao> avaliacaos, Set<Ocupacao> ocupacaos) {
        this.codEdificacao = codEdificacao;
        this.tipoEdificacao = tipoEdificacao;
        this.tipoConstrucao = tipoConstrucao;
        this.bemImovel = bemImovel;
        this.especificacao = especificacao;
        this.logradouro = logradouro;
        this.areaConstruida = areaConstruida;
        this.areaUtilizada = areaUtilizada;
        this.dataAverbacao = dataAverbacao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
        this.documentacaos = documentacaos;
        this.lotes = lotes;
        this.avaliacaos = avaliacaos;
        this.ocupacaos = ocupacaos;
    }

    public Integer getCodEdificacao() {
        return this.codEdificacao;
    }

    public void setCodEdificacao(Integer codEdificacao) {
        this.codEdificacao = codEdificacao;
    }

    public TipoEdificacao getTipoEdificacao() {
        return this.tipoEdificacao;
    }

    public void setTipoEdificacao(TipoEdificacao tipoEdificacao) {
        this.tipoEdificacao = tipoEdificacao;
    }

    public TipoConstrucao getTipoConstrucao() {
        return this.tipoConstrucao;
    }

    public void setTipoConstrucao(TipoConstrucao tipoConstrucao) {
        this.tipoConstrucao = tipoConstrucao;
    }

    public BemImovel getBemImovel() {
        return this.bemImovel;
    }

    public void setBemImovel(BemImovel bemImovel) {
        this.bemImovel = bemImovel;
    }

    public String getEspecificacao() {
        return this.especificacao;
    }

    public void setEspecificacao(String especificacao) {
        this.especificacao = especificacao;
    }

    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public BigDecimal getAreaConstruida() {
        return this.areaConstruida;
    }

    public void setAreaConstruida(BigDecimal areaConstruida) {
        this.areaConstruida = areaConstruida;
    }

    public BigDecimal getAreaUtilizada() {
        return this.areaUtilizada;
    }

    public void setAreaUtilizada(BigDecimal areaUtilizada) {
        this.areaUtilizada = areaUtilizada;
    }

    public Date getDataAverbacao() {
        return this.dataAverbacao;
    }

    public void setDataAverbacao(Date dataAverbacao) {
        this.dataAverbacao = dataAverbacao;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Set<Documentacao> getDocumentacaos() {
        return this.documentacaos;
    }

    public void setDocumentacaos(Set<Documentacao> documentacaos) {
        this.documentacaos = documentacaos;
    }

    public Set<Lote> getLotes() {
        return this.lotes;
    }

    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }

    public Set<Avaliacao> getAvaliacaos() {
        return this.avaliacaos;
    }

    public void setAvaliacaos(Set<Avaliacao> avaliacaos) {
        this.avaliacaos = avaliacaos;
    }

    public Set<Ocupacao> getOcupacaos() {
        return this.ocupacaos;
    }

    public void setOcupacaos(Set<Ocupacao> ocupacaos) {
        this.ocupacaos = ocupacaos;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof Edificacao)) {
            return false;
        }

        Edificacao castOther = (Edificacao) other;

        return (this.getCodEdificacao().equals( castOther.getCodEdificacao()));
    }

    public int hashCode() {
        int result = 17;

        result = (37 * result) + this.getCodEdificacao();

        return result;
    }

	public Set<Vistoria> getListaVistoria() {
		return listaVistoria;
	}
	
	public void setListaVistoria(Set<Vistoria> listaVistoria) {
		this.listaVistoria = listaVistoria;
	}

	public Set<ItemDoacao> getListaItemDoacao() {
		return listaItemDoacao;
	}

	public void setListaItemDoacao(Set<ItemDoacao> listaItemDoacao) {
		this.listaItemDoacao = listaItemDoacao;
	}

	public Set<ItemTransferencia> getListaItemTransferencia() {
		return listaItemTransferencia;
	}

	public void setListaItemTransferencia(
			Set<ItemTransferencia> listaItemTransferencia) {
		this.listaItemTransferencia = listaItemTransferencia;
	}

	
}
