package gov.pr.celepar.abi.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;


/**
 * Cartorio generated by hbm2java
 */
public class Instituicao implements java.io.Serializable {
   
	
	private static final long serialVersionUID = 6381954417092762083L;
	private Integer codInstituicao;
    private String sigla;
    private String siglaDescricao;
    
    private String cpfResponsavelCriacao;
    private String cpfResponsavelAtualizacao;
    
    private String cep;
    private String uf;
    private String municipio;
    private Integer codMunicipio;
    private String logradouro;
    private String numero;
    private String bairroDistrito;
    private String complemento;
    private String contato;
    private String telefoneDdd;
    private String telefoneNumero;
    
    private String descricaoRelatorio;
    private String logoInstituicao;
    private String nome;
    private String email;
    
    private Date tsInclusao;
    private Date tsAtualizacao;
    
    private Set<CargoAssinatura> listaCargoAssinatura = new HashSet<CargoAssinatura>(0);
    private Set<Assinatura> listaAssinatura = new HashSet<Assinatura>(0);
    private Set<Usuario> listaUsuario = new HashSet<Usuario>(0);
    private Set<BemImovel> listaBemImovel = new HashSet<BemImovel>(0);
    private Set<Orgao> listaOrgao = new HashSet<Orgao>(0);
    private Set<Vistoriador> listaVistoriador = new HashSet<Vistoriador>(0);
    private Set<Doacao> listaDoacao = new HashSet<Doacao>(0);
    private Set<Transferencia> listaTransferencia = new HashSet<Transferencia>(0);
    private Set<CessaoDeUso> listaCessaoDeUso = new HashSet<CessaoDeUso>(0);
    private Set<ParametroVistoria> listaParametroVistoria = new HashSet<ParametroVistoria>(0);
    
    public Instituicao() {
    }

	public Integer getCodInstituicao() {
		return codInstituicao;
	}

	public void setCodInstituicao(Integer codInstituicao) {
		this.codInstituicao = codInstituicao;
	}

	public String getSigla() {
		return sigla;
	}

	public void setSigla(String sigla) {
		this.sigla = sigla;
	}

	public String getCpfResponsavelCriacao() {
		return cpfResponsavelCriacao;
	}

	public void setCpfResponsavelCriacao(String cpfResponsavelCriacao) {
		this.cpfResponsavelCriacao = cpfResponsavelCriacao;
	}

	public String getCpfResponsavelAtualizacao() {
		return cpfResponsavelAtualizacao;
	}

	public void setCpfResponsavelAtualizacao(String cpfResponsavelAtualizacao) {
		this.cpfResponsavelAtualizacao = cpfResponsavelAtualizacao;
	}

	public String getCep() {
		return cep;
	}

	public void setCep(String cep) {
		this.cep = cep;
	}

	public String getUf() {
		return uf;
	}

	public void setUf(String uf) {
		this.uf = uf;
	}

	public String getMunicipio() {
		return municipio;
	}

	public void setMunicipio(String municipio) {
		this.municipio = municipio;
	}

	public Integer getCodMunicipio() {
		return codMunicipio;
	}

	public void setCodMunicipio(Integer codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public String getLogradouro() {
		return logradouro;
	}

	public void setLogradouro(String logradouro) {
		this.logradouro = logradouro;
	}

	public String getNumero() {
		return numero;
	}

	public void setNumero(String numero) {
		this.numero = numero;
	}

	public String getBairroDistrito() {
		return bairroDistrito;
	}

	public void setBairroDistrito(String bairroDistrito) {
		this.bairroDistrito = bairroDistrito;
	}

	public String getComplemento() {
		return complemento;
	}

	public void setComplemento(String complemento) {
		this.complemento = complemento;
	}

	public String getContato() {
		return contato;
	}

	public void setContato(String contato) {
		this.contato = contato;
	}

	public String getTelefoneDdd() {
		return telefoneDdd;
	}

	public void setTelefoneDdd(String telefoneDdd) {
		this.telefoneDdd = telefoneDdd;
	}

	public String getTelefoneNumero() {
		return telefoneNumero;
	}

	public void setTelefoneNumero(String telefoneNumero) {
		this.telefoneNumero = telefoneNumero;
	}

	public String getDescricaoRelatorio() {
		return descricaoRelatorio;
	}

	public void setDescricaoRelatorio(String descricaoRelatorio) {
		this.descricaoRelatorio = descricaoRelatorio;
	}

	public String getLogoInstituicao() {
		return logoInstituicao;
	}

	public void setLogoInstituicao(String logoInstituicao) {
		this.logoInstituicao = logoInstituicao;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getEmail() {
		return email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public Date getTsInclusao() {
		return tsInclusao;
	}

	public void setTsInclusao(Date tsInclusao) {
		this.tsInclusao = tsInclusao;
	}

	public Date getTsAtualizacao() {
		return tsAtualizacao;
	}

	public void setTsAtualizacao(Date tsAtualizacao) {
		this.tsAtualizacao = tsAtualizacao;
	}

	public Set<CargoAssinatura> getListaCargoAssinatura() {
		return listaCargoAssinatura;
	}

	public void setListaCargoAssinatura(Set<CargoAssinatura> listaCargoAssinatura) {
		this.listaCargoAssinatura = listaCargoAssinatura;
	}

	public Set<Usuario> getListaUsuario() {
		return listaUsuario;
	}

	public void setListaUsuario(Set<Usuario> listaUsuario) {
		this.listaUsuario = listaUsuario;
	}

	public Set<BemImovel> getListaBemImovel() {
		return listaBemImovel;
	}

	public void setListaBemImovel(Set<BemImovel> listaBemImovel) {
		this.listaBemImovel = listaBemImovel;
	}

	public Set<Orgao> getListaOrgao() {
		return listaOrgao;
	}

	public void setListaOrgao(Set<Orgao> listaOrgao) {
		this.listaOrgao = listaOrgao;
	}

	public Set<Vistoriador> getListaVistoriador() {
		return listaVistoriador;
	}

	public void setListaVistoriador(Set<Vistoriador> listaVistoriador) {
		this.listaVistoriador = listaVistoriador;
	}

	@Transient
	public String getSiglaDescricao() {
		if (getSigla() != null && getSigla().trim().length() > 0) {
			return this.getSigla().concat(" - ").concat(this.getNome());
		}
		return this.getNome();
	}

	public void setListaDoacao(Set<Doacao> listaDoacao) {
		this.listaDoacao = listaDoacao;
	}

	public Set<Doacao> getListaDoacao() {
		return listaDoacao;
	}

	public void setListaAssinatura(Set<Assinatura> listaAssinatura) {
		this.listaAssinatura = listaAssinatura;
	}

	public Set<Assinatura> getListaAssinatura() {
		return listaAssinatura;
	}

	public Set<ParametroVistoria> getListaParametroVistoria() {
		return listaParametroVistoria;
	}

	public void setListaParametroVistoria(Set<ParametroVistoria> listaParametroVistoria) {
		this.listaParametroVistoria = listaParametroVistoria;
	}

	public void setSiglaDescricao(String siglaDescricao) {
		this.siglaDescricao = siglaDescricao;
	}
	
	public Set<Transferencia> getListaTransferencia() {
		return listaTransferencia;
	}

	public void setListaTransferencia(Set<Transferencia> listaTransferencia) {
		this.listaTransferencia = listaTransferencia;
	}

	public Set<CessaoDeUso> getListaCessaoDeUso() {
		return listaCessaoDeUso;
	}

	public void setListaCessaoDeUso(Set<CessaoDeUso> listaCessaoDeUso) {
		this.listaCessaoDeUso = listaCessaoDeUso;
	}
    
}
