package gov.pr.celepar.abi.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * LeiBemImovel generated by hbm2java
 */
public class LeiBemImovel implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -1760385281854966971L;
	private Integer codLeiBemImovel;
    private BemImovel bemImovel;
    private TipoLeiBemImovel tipoLeiBemImovel;
    private Long numero;
    private Date dataAssinatura;
    private Date dataPublicacao;
    private Date tsInclusao;
    private Date tsAtualizacao;
    private String cpfResponsavel;
    private Long nrDioe;
    private Set<Doacao> listaDoacao = new HashSet<Doacao>(0);

    public LeiBemImovel() {
    }

    public LeiBemImovel(Integer codLeiBemImovel, BemImovel bemImovel,
        TipoLeiBemImovel tipoLeiBemImovel, Long numero, Date dataAssinatura,
        Date dataPublicacao, Date tsInclusao, Date tsAtualizacao,
        String cpfResponsavel) {
        this.codLeiBemImovel = codLeiBemImovel;
        this.bemImovel = bemImovel;
        this.tipoLeiBemImovel = tipoLeiBemImovel;
        this.numero = numero;
        this.dataAssinatura = dataAssinatura;
        this.dataPublicacao = dataPublicacao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
    }

    public Integer getCodLeiBemImovel() {
        return this.codLeiBemImovel;
    }

    public void setCodLeiBemImovel(Integer codLeiBemImovel) {
        this.codLeiBemImovel = codLeiBemImovel;
    }

    public BemImovel getBemImovel() {
        return this.bemImovel;
    }

    public void setBemImovel(BemImovel bemImovel) {
        this.bemImovel = bemImovel;
    }

    public TipoLeiBemImovel getTipoLeiBemImovel() {
        return this.tipoLeiBemImovel;
    }

    public void setTipoLeiBemImovel(TipoLeiBemImovel tipoLeiBemImovel) {
        this.tipoLeiBemImovel = tipoLeiBemImovel;
    }

    public Long getNumero() {
        return this.numero;
    }

    public void setNumero(Long numero) {
        this.numero = numero;
    }

    public Date getDataAssinatura() {
        return this.dataAssinatura;
    }

    public void setDataAssinatura(Date dataAssinatura) {
        this.dataAssinatura = dataAssinatura;
    }

    public Date getDataPublicacao() {
        return this.dataPublicacao;
    }

    public void setDataPublicacao(Date dataPublicacao) {
        this.dataPublicacao = dataPublicacao;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

   

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		LeiBemImovel other = (LeiBemImovel) obj;
		if (codLeiBemImovel == null) {
			if (other.codLeiBemImovel != null)
				return false;
		} else if (!codLeiBemImovel.equals(other.codLeiBemImovel))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codLeiBemImovel == null) ? 0 : codLeiBemImovel.hashCode());
		return result;
	}

	public void setListaDoacao(Set<Doacao> listaDoacao) {
		this.listaDoacao = listaDoacao;
	}

	public Set<Doacao> getListaDoacao() {
		return listaDoacao;
	}

	public void setNrDioe(Long nrDioe) {
		this.nrDioe = nrDioe;
	}

	public Long getNrDioe() {
		return nrDioe;
	}
}
