package gov.pr.celepar.abi.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;


/**
 * Lote generated by hbm2java
 */
public class Lote implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -2357102844668587621L;
	private Integer codLote;
    private Quadra quadra;
    private String descricao;
    private Date tsInclusao;
    private Date tsAtualizacao;
    private String cpfResponsavel;
    private Set<Edificacao> edificacaos = new HashSet<Edificacao>(0);

    public Lote() {
    }

    public Lote(Integer codLote, Quadra quadra, String descricao, Date tsInclusao,
        Date tsAtualizacao, String cpfResponsavel) {
        this.codLote = codLote;
        this.quadra = quadra;
        this.descricao = descricao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
    }

    public Lote(Integer codLote, Quadra quadra, String descricao, Date tsInclusao,
        Date tsAtualizacao, String cpfResponsavel,
        Set<Edificacao> edificacaos) {
        this.codLote = codLote;
        this.quadra = quadra;
        this.descricao = descricao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
        this.edificacaos = edificacaos;
    }

    public Integer getCodLote() {
        return this.codLote;
    }

    public void setCodLote(Integer codLote) {
        this.codLote = codLote;
    }

    public Quadra getQuadra() {
        return this.quadra;
    }

    public void setQuadra(Quadra quadra) {
        this.quadra = quadra;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Set<Edificacao> getEdificacaos() {
        return this.edificacaos;
    }

    public void setEdificacaos(Set<Edificacao> edificacaos) {
        this.edificacaos = edificacaos;
    }

   

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Lote other = (Lote) obj;
		if (codLote == null) {
			if (other.codLote != null)
				return false;
		} else if (!codLote.equals(other.codLote))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((codLote == null) ? 0 : codLote.hashCode());
		return result;
	}
}
