package gov.pr.celepar.abi.pojo;

import java.util.Date;


/**
 * Notificacao generated by hbm2java
 */
public class Notificacao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 6293176816027928996L;
	private Integer codNotificacao;
    private Documentacao documentacao;
    private String descricao;
    private Date dataNotificacao;
    private Date prazoNotificacao;
    private Date dataSolucao;
    private String motivo;
    private String cpfResponsavel;
    private Date tsInclusao;
    private Date tsAlteracao;

    public Notificacao() {
    }

    public Notificacao(Integer codNotificacao, Documentacao documentacao,
        String descricao, Date dataNotificacao, Date prazoNotificacao,
        String cpfResponsavel, Date tsInclusao, Date tsAlteracao) {
        this.codNotificacao = codNotificacao;
        this.documentacao = documentacao;
        this.descricao = descricao;
        this.dataNotificacao = dataNotificacao;
        this.prazoNotificacao = prazoNotificacao;
        this.cpfResponsavel = cpfResponsavel;
        this.tsInclusao = tsInclusao;
        this.tsAlteracao = tsAlteracao;
    }

    public Notificacao(Integer codNotificacao, Documentacao documentacao,
        String descricao, Date dataNotificacao, Date prazoNotificacao,
        Date dataSolucao, String motivo, String cpfResponsavel,
        Date tsInclusao, Date tsAlteracao) {
        this.codNotificacao = codNotificacao;
        this.documentacao = documentacao;
        this.descricao = descricao;
        this.dataNotificacao = dataNotificacao;
        this.prazoNotificacao = prazoNotificacao;
        this.dataSolucao = dataSolucao;
        this.motivo = motivo;
        this.cpfResponsavel = cpfResponsavel;
        this.tsInclusao = tsInclusao;
        this.tsAlteracao = tsAlteracao;
    }

    public Integer getCodNotificacao() {
        return this.codNotificacao;
    }

    public void setCodNotificacao(Integer codNotificacao) {
        this.codNotificacao = codNotificacao;
    }

    public Documentacao getDocumentacao() {
        return this.documentacao;
    }

    public void setDocumentacao(Documentacao documentacao) {
        this.documentacao = documentacao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getDataNotificacao() {
        return this.dataNotificacao;
    }

    public void setDataNotificacao(Date dataNotificacao) {
        this.dataNotificacao = dataNotificacao;
    }

    public Date getPrazoNotificacao() {
        return this.prazoNotificacao;
    }

    public void setPrazoNotificacao(Date prazoNotificacao) {
        this.prazoNotificacao = prazoNotificacao;
    }

    public Date getDataSolucao() {
        return this.dataSolucao;
    }

    public void setDataSolucao(Date dataSolucao) {
        this.dataSolucao = dataSolucao;
    }

    public String getMotivo() {
        return this.motivo;
    }

    public void setMotivo(String motivo) {
        this.motivo = motivo;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public Date getTsAlteracao() {
        return this.tsAlteracao;
    }

    public void setTsAlteracao(Date tsAlteracao) {
        this.tsAlteracao = tsAlteracao;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Notificacao other = (Notificacao) obj;
		if (codNotificacao == null) {
			if (other.codNotificacao != null)
				return false;
		} else if (!codNotificacao.equals(other.codNotificacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codNotificacao == null) ? 0 : codNotificacao.hashCode());
		return result;
	}
}
