package gov.pr.celepar.abi.pojo;

import java.util.Date;

import javax.persistence.Transient;


/**
 * OcorrenciaDocumentacao generated by hbm2java
 */
public class OcorrenciaDocumentacao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -3339048970491222827L;
	private Integer codOcorrenciaDocumentacao;
    private Documentacao documentacao;
    private BemImovel bemImovel;
    private String descricao;
    private Date tsInclusao;
    private String cpfResponsavel;
    private Date tsAtualizacao;
    private String nomeResponsavel;
 

    @Transient
    public OcorrenciaDocumentacao getInstanciaAtual(){
    	return this;
    }
    
    public OcorrenciaDocumentacao() {
    }

    public OcorrenciaDocumentacao(Integer codOcorrenciaDocumentacao,
        Documentacao documentacao, BemImovel bemImovel, String descricao,
        Date tsInclusao, String cpfResponsavel, Date tsAtualizacao) {
        this.codOcorrenciaDocumentacao = codOcorrenciaDocumentacao;
        this.documentacao = documentacao;
        this.bemImovel = bemImovel;
        this.descricao = descricao;
        this.tsInclusao = tsInclusao;
        this.cpfResponsavel = cpfResponsavel;
        this.tsAtualizacao = tsAtualizacao;
    }

    public Integer getCodOcorrenciaDocumentacao() {
        return this.codOcorrenciaDocumentacao;
    }

    public void setCodOcorrenciaDocumentacao(Integer codOcorrenciaDocumentacao) {
        this.codOcorrenciaDocumentacao = codOcorrenciaDocumentacao;
    }

    public Documentacao getDocumentacao() {
        return this.documentacao;
    }

    public void setDocumentacao(Documentacao documentacao) {
        this.documentacao = documentacao;
    }

    public BemImovel getBemImovel() {
        return this.bemImovel;
    }

    public void setBemImovel(BemImovel bemImovel) {
        this.bemImovel = bemImovel;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		OcorrenciaDocumentacao other = (OcorrenciaDocumentacao) obj;
		if (codOcorrenciaDocumentacao == null) {
			if (other.codOcorrenciaDocumentacao != null)
				return false;
		} else if (!codOcorrenciaDocumentacao
				.equals(other.codOcorrenciaDocumentacao))
			return false;
		return true;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codOcorrenciaDocumentacao == null) ? 0
						: codOcorrenciaDocumentacao.hashCode());
		return result;
	}

	public void setNomeResponsavel(String nomeResponsavel) {
		this.nomeResponsavel = nomeResponsavel;
	}

	public String getNomeResponsavel() {
		return nomeResponsavel;
	}
}
