package gov.pr.celepar.abi.pojo;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Ocupacao generated by hbm2java
 */
public class Ocupacao implements java.io.Serializable {
    
	private static final long serialVersionUID = 8062871277446839923L;
	private Integer codOcupacao;
    private Edificacao edificacao;
    private BemImovel bemImovel;
    private Orgao orgao;
    private SituacaoOcupacao situacaoOcupacao;
    private String descricao;
    private BigDecimal ocupacaoMetroQuadrado;
    private BigDecimal ocupacaoPercentual;
    private Date tsInclusao;
    private String cpfResponsavel;
    private Date tsAtualizacao;
    private Date dataOcupacao;
    private String termoTransferencia;
    private String numeroLei;
    private Date dataLei;
    private String vigenciaLei;
    private String numeroNotificacao;
    private Date dataNotificacao;
    private String prazoNotificacao;
    private Integer protocoloNotificacaoSpi;
    private Boolean ativo;

    public Ocupacao() {
    }

    public Ocupacao(Integer codOcupacao, Edificacao edificacao, Orgao orgao, SituacaoOcupacao situacaoOcupacao,
        String descricao, Date tsInclusao, String cpfResponsavel,
        Date tsAtualizacao) {
        this.codOcupacao = codOcupacao;
        this.edificacao = edificacao;
        this.orgao = orgao;
        this.situacaoOcupacao = situacaoOcupacao;
        this.descricao = descricao;
        this.tsInclusao = tsInclusao;
        this.cpfResponsavel = cpfResponsavel;
        this.tsAtualizacao = tsAtualizacao;
    }

    public Ocupacao(Integer codOcupacao, Edificacao edificacao, Orgao orgao, SituacaoOcupacao situacaoOcupacao,
        String descricao, BigDecimal ocupacaoMetroQuadrado,
        BigDecimal ocupacaoPercentual, Date tsInclusao,
        String cpfResponsavel, Date tsAtualizacao, Date dataOcupacao,
        String termoTransferencia, String numeroLei, Date dataLei,
        String vigenciaLei, String numeroNotificacao, Date dataNotificacao,
        String prazoNotificacao, Integer protocoloNotificacaoSpi, BemImovel bemImovel, Boolean ativo) {
        this.codOcupacao = codOcupacao;
        this.edificacao = edificacao;
        this.orgao = orgao;
        this.situacaoOcupacao = situacaoOcupacao;
        this.descricao = descricao;
        this.ocupacaoMetroQuadrado = ocupacaoMetroQuadrado;
        this.ocupacaoPercentual = ocupacaoPercentual;
        this.tsInclusao = tsInclusao;
        this.cpfResponsavel = cpfResponsavel;
        this.tsAtualizacao = tsAtualizacao;
        this.dataOcupacao = dataOcupacao;
        this.termoTransferencia = termoTransferencia;
        this.numeroLei = numeroLei;
        this.dataLei = dataLei;
        this.vigenciaLei = vigenciaLei;
        this.numeroNotificacao = numeroNotificacao;
        this.dataNotificacao = dataNotificacao;
        this.prazoNotificacao = prazoNotificacao;
        this.protocoloNotificacaoSpi = protocoloNotificacaoSpi;
        this.bemImovel = bemImovel;
        this.ativo = ativo;
    }

    public Integer getCodOcupacao() {
        return this.codOcupacao;
    }

    public void setCodOcupacao(Integer codOcupacao) {
        this.codOcupacao = codOcupacao;
    }

    public Edificacao getEdificacao() {
        return this.edificacao;
    }

    public void setEdificacao(Edificacao edificacao) {
        this.edificacao = edificacao;
    }
    
    public Orgao getOrgao() {
        return this.orgao;
    }

    public void setOrgao(Orgao orgao) {
        this.orgao = orgao;
    }

    public SituacaoOcupacao getSituacaoOcupacao() {
        return this.situacaoOcupacao;
    }

    public void setSituacaoOcupacao(SituacaoOcupacao situacaoOcupacao) {
        this.situacaoOcupacao = situacaoOcupacao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public BigDecimal getOcupacaoMetroQuadrado() {
        return this.ocupacaoMetroQuadrado;
    }

    public void setOcupacaoMetroQuadrado(BigDecimal ocupacaoMetroQuadrado) {
        this.ocupacaoMetroQuadrado = ocupacaoMetroQuadrado;
    }

    public BigDecimal getOcupacaoPercentual() {
        return this.ocupacaoPercentual;
    }

    public void setOcupacaoPercentual(BigDecimal ocupacaoPercentual) {
        this.ocupacaoPercentual = ocupacaoPercentual;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public Date getDataOcupacao() {
        return this.dataOcupacao;
    }

    public void setDataOcupacao(Date dataOcupacao) {
        this.dataOcupacao = dataOcupacao;
    }

    public String getTermoTransferencia() {
        return this.termoTransferencia;
    }

    public void setTermoTransferencia(String termoTransferencia) {
        this.termoTransferencia = termoTransferencia;
    }

    public String getNumeroLei() {
        return this.numeroLei;
    }

    public void setNumeroLei(String numeroLei) {
        this.numeroLei = numeroLei;
    }

    public Date getDataLei() {
        return this.dataLei;
    }

    public void setDataLei(Date dataLei) {
        this.dataLei = dataLei;
    }

    public String getVigenciaLei() {
        return this.vigenciaLei;
    }

    public void setVigenciaLei(String vigenciaLei) {
        this.vigenciaLei = vigenciaLei;
    }

    public String getNumeroNotificacao() {
        return this.numeroNotificacao;
    }

    public void setNumeroNotificacao(String numeroNotificacao) {
        this.numeroNotificacao = numeroNotificacao;
    }

    public Date getDataNotificacao() {
        return this.dataNotificacao;
    }

    public void setDataNotificacao(Date dataNotificacao) {
        this.dataNotificacao = dataNotificacao;
    }

    public String getPrazoNotificacao() {
        return this.prazoNotificacao;
    }

    public void setPrazoNotificacao(String prazoNotificacao) {
        this.prazoNotificacao = prazoNotificacao;
    }

    public Integer getProtocoloNotificacaoSpi() {
        return this.protocoloNotificacaoSpi;
    }

    public void setProtocoloNotificacaoSpi(Integer protocoloNotificacaoSpi) {
        this.protocoloNotificacaoSpi = protocoloNotificacaoSpi;
    }

	public void setBemImovel(BemImovel bemImovel) {
		this.bemImovel = bemImovel;
	}

	public BemImovel getBemImovel() {
		return bemImovel;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Ocupacao other = (Ocupacao) obj;
		if (codOcupacao == null) {
			if (other.codOcupacao != null)
				return false;
		} else if (!codOcupacao.equals(other.codOcupacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codOcupacao == null) ? 0 : codOcupacao.hashCode());
		return result;
	}

	public void setAtivo(Boolean ativo) {
		this.ativo = ativo;
	}

	public Boolean getAtivo() {
		return ativo;
	}

}
