package gov.pr.celepar.abi.pojo;

import gov.pr.celepar.abi.enumeration.TipoAdministracao;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;


/**
 * Orgao generated by hbm2java
 */
public class Orgao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 6797935221442304612L;
	private Integer codOrgao;
    private String sigla;
    private String descricao;
	private Integer indTipoAdministracao;
	private Instituicao instituicao;
    private Set<Ocupacao> ocupacaos = new HashSet<Ocupacao>(0);
    private Set<BemImovel> bemImovels = new HashSet<BemImovel>(0);
    private Set<Assinatura> listaAssinatura = new HashSet<Assinatura>(0);
    private Set<Doacao> listaDoacaoProprietario = new HashSet<Doacao>(0);
    private Set<Doacao> listaDoacaoResponsavel = new HashSet<Doacao>(0);
    private Set<Transferencia> listaTransferenciaCedente = new HashSet<Transferencia>(0);
    private Set<Transferencia> listaTransferenciaCessionario = new HashSet<Transferencia>(0);
    private Set<Usuario> listaUsuario = new HashSet<Usuario>(0);
	private Set<UsuarioOrgao> listaUsuarioOrgao = new HashSet<UsuarioOrgao>(0);
    
	public Orgao() {
    }

    public Orgao(Integer codOrgao, String descricao, String sigla) {
        this.codOrgao = codOrgao;
        this.descricao = descricao;
        this.sigla = sigla;
    }

    public Orgao(Integer codOrgao, String descricao, String sigla,
        Set<Ocupacao> ocupacaos, Set<BemImovel> bemImovels, Integer indTipoAdministracao) {
        this.codOrgao = codOrgao;
        this.descricao = descricao;
        this.sigla = sigla;
        this.ocupacaos = ocupacaos;
        this.bemImovels = bemImovels;
        this.indTipoAdministracao = indTipoAdministracao;
    }

    public Integer getCodOrgao() {
        return this.codOrgao;
    }

    public void setCodOrgao(Integer codOrgao) {
        this.codOrgao = codOrgao;
    }
    
    public String getSigla() {
        return this.sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<Ocupacao> getOcupacaos() {
        return this.ocupacaos;
    }

    public void setOcupacaos(Set<Ocupacao> ocupacaos) {
        this.ocupacaos = ocupacaos;
    }

    public Set<BemImovel> getBemImovels() {
        return this.bemImovels;
    }

    public void setBemImovels(Set<BemImovel> bemImovels) {
        this.bemImovels = bemImovels;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Orgao other = (Orgao) obj;
		if (codOrgao == null) {
			if (other.codOrgao != null)
				return false;
		} else if (!codOrgao.equals(other.codOrgao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codOrgao == null) ? 0 : codOrgao.hashCode());
		return result;
	}

	public void setIndTipoAdministracao(Integer indTipoAdministracao) {
		this.indTipoAdministracao = indTipoAdministracao;
	}

	public Integer getIndTipoAdministracao() {
		return indTipoAdministracao;
	}
	@Transient
	public String getDescricaoTipoAdministracao() {
		String aux = "";
		if (getIndTipoAdministracao() != null){
			aux = TipoAdministracao.getDescricao(getIndTipoAdministracao());
		}
		return aux;
	}
	
    public Set<Transferencia> getListaTransferenciaCedente() {
		return listaTransferenciaCedente;
	}

	public void setListaTransferenciaCedente(
			Set<Transferencia> listaTransferenciaCedente) {
		this.listaTransferenciaCedente = listaTransferenciaCedente;
	}

	public Set<Transferencia> getListaTransferenciaCessionario() {
		return listaTransferenciaCessionario;
	}

	public void setListaTransferenciaCessionario(
			Set<Transferencia> listaTransferenciaCessionario) {
		this.listaTransferenciaCessionario = listaTransferenciaCessionario;
	}

	public Set<Doacao> getListaDoacaoProprietario() {
		return listaDoacaoProprietario;
	}

	public void setListaDoacaoProprietario(Set<Doacao> listaDoacaoProprietario) {
		this.listaDoacaoProprietario = listaDoacaoProprietario;
	}

	public Set<Doacao> getListaDoacaoResponsavel() {
		return listaDoacaoResponsavel;
	}

	public void setListaDoacaoResponsavel(Set<Doacao> listaDoacaoResponsavel) {
		this.listaDoacaoResponsavel = listaDoacaoResponsavel;
	}

	public void setListaAssinatura(Set<Assinatura> listaAssinatura) {
		this.listaAssinatura = listaAssinatura;
	}

	public Set<Assinatura> getListaAssinatura() {
		return listaAssinatura;
	}

	@Transient
	public String getSiglaDescricao() {
		String aux = "";
		aux = aux.concat(this.getSigla());
		aux = aux.concat(" - ");
		aux = aux.concat(this.getDescricao());
		return aux;
	}

	public Set<Usuario> getListaUsuario() {
		return listaUsuario;
	}

	public void setListaUsuario(Set<Usuario> listaUsuario) {
		this.listaUsuario = listaUsuario;
	}

	public void setListaUsuarioOrgao(Set<UsuarioOrgao> listaUsuarioOrgao) {
		this.listaUsuarioOrgao = listaUsuarioOrgao;
	}

	public Set<UsuarioOrgao> getListaUsuarioOrgao() {
		return listaUsuarioOrgao;
	}

	public Instituicao getInstituicao() {
		return instituicao;
	}

	public void setInstituicao(Instituicao instituicao) {
		this.instituicao = instituicao;
	}

}
