package gov.pr.celepar.abi.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;


/**
 * Quadra generated by hbm2java
 */
public class Quadra implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4146714995329463147L;
	private Integer codQuadra;
    private BemImovel bemImovel;
    private String descricao;
    private Date tsInclusao;
    private Date tsAtualizacao;
    private String cpfResponsavel;
    private Set<Lote> lotes = new HashSet<Lote>(0);

    public Quadra() {
    }

    public Quadra(Integer codQuadra, BemImovel bemImovel, String descricao,
        Date tsInclusao, Date tsAtualizacao, String cpfResponsavel) {
        this.codQuadra = codQuadra;
        this.bemImovel = bemImovel;
        this.descricao = descricao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
    }

    public Quadra(Integer codQuadra, BemImovel bemImovel, String descricao,
        Date tsInclusao, Date tsAtualizacao, String cpfResponsavel,
        Set<Lote> lotes) {
        this.codQuadra = codQuadra;
        this.bemImovel = bemImovel;
        this.descricao = descricao;
        this.tsInclusao = tsInclusao;
        this.tsAtualizacao = tsAtualizacao;
        this.cpfResponsavel = cpfResponsavel;
        this.lotes = lotes;
    }

    public Integer getCodQuadra() {
        return this.codQuadra;
    }

    public void setCodQuadra(Integer codQuadra) {
        this.codQuadra = codQuadra;
    }

    public BemImovel getBemImovel() {
        return this.bemImovel;
    }

    public void setBemImovel(BemImovel bemImovel) {
        this.bemImovel = bemImovel;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Date getTsInclusao() {
        return this.tsInclusao;
    }

    public void setTsInclusao(Date tsInclusao) {
        this.tsInclusao = tsInclusao;
    }

    public Date getTsAtualizacao() {
        return this.tsAtualizacao;
    }

    public void setTsAtualizacao(Date tsAtualizacao) {
        this.tsAtualizacao = tsAtualizacao;
    }

    public String getCpfResponsavel() {
		return cpfResponsavel;
	}
    
    public void setCpfResponsavel(String cpfResponsavel) {
		this.cpfResponsavel = cpfResponsavel;
	}

    public Set<Lote> getLotes() {
        return this.lotes;
    }

    public void setLotes(Set<Lote> lotes) {
        this.lotes = lotes;
    }
    
    @Transient
    public String getDescricaoLotes() {
    	if (getLotes()!= null && getLotes().size()>0){
    		StringBuffer aux = new StringBuffer();
    		for (Lote l: getLotes()){
    			aux.append(l.getDescricao()).append("\n");
    		}
    		
    		return aux.toString();
    	}else{
    		return "";
    	}
    }

   

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Quadra other = (Quadra) obj;
		if (codQuadra == null) {
			if (other.codQuadra != null)
				return false;
		} else if (!codQuadra.equals(other.codQuadra))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codQuadra == null) ? 0 : codQuadra.hashCode());
		return result;
	}
}
