package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * SituacaoOcupacao generated by hbm2java
 */
public class SituacaoOcupacao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -2037301741092304009L;
	private Integer codSituacaoOcupacao;
    private String descricao;
    private Set<Ocupacao> ocupacaos = new HashSet<Ocupacao>(0);

    public SituacaoOcupacao() {
    }

    public SituacaoOcupacao(Integer codSituacaoOcupacao, String descricao) {
        this.codSituacaoOcupacao = codSituacaoOcupacao;
        this.descricao = descricao;
    }

    public SituacaoOcupacao(Integer codSituacaoOcupacao, String descricao,
        Set<Ocupacao> ocupacaos) {
        this.codSituacaoOcupacao = codSituacaoOcupacao;
        this.descricao = descricao;
        this.ocupacaos = ocupacaos;
    }

    public Integer getCodSituacaoOcupacao() {
        return this.codSituacaoOcupacao;
    }

    public void setCodSituacaoOcupacao(Integer codSituacaoOcupacao) {
        this.codSituacaoOcupacao = codSituacaoOcupacao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<Ocupacao> getOcupacaos() {
        return this.ocupacaos;
    }

    public void setOcupacaos(Set<Ocupacao> ocupacaos) {
        this.ocupacaos = ocupacaos;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SituacaoOcupacao other = (SituacaoOcupacao) obj;
		if (codSituacaoOcupacao == null) {
			if (other.codSituacaoOcupacao != null)
				return false;
		} else if (!codSituacaoOcupacao.equals(other.codSituacaoOcupacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codSituacaoOcupacao == null) ? 0 : codSituacaoOcupacao
						.hashCode());
		return result;
	}
}
