package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * SituacaoLegalCartorial generated by hbm2java
 */
public class SituacaoLegalCartorial implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -4003181294628413010L;
	private Integer codSituacaoLegalCartorial;
    private String descricao;
    private Set<BemImovel> bemImovels = new HashSet<BemImovel>(0);

    public SituacaoLegalCartorial() {
    }

    public SituacaoLegalCartorial(Integer codSituacaoLegalCartorial,
        String descricao) {
        this.codSituacaoLegalCartorial = codSituacaoLegalCartorial;
        this.descricao = descricao;
    }

    public SituacaoLegalCartorial(Integer codSituacaoLegalCartorial,
        String descricao, Set<BemImovel> bemImovels) {
        this.codSituacaoLegalCartorial = codSituacaoLegalCartorial;
        this.descricao = descricao;
        this.bemImovels = bemImovels;
    }

    public Integer getCodSituacaoLegalCartorial() {
        return this.codSituacaoLegalCartorial;
    }

    public void setCodSituacaoLegalCartorial(Integer codSituacaoLegalCartorial) {
        this.codSituacaoLegalCartorial = codSituacaoLegalCartorial;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<BemImovel> getBemImovels() {
        return this.bemImovels;
    }

    public void setBemImovels(Set<BemImovel> bemImovels) {
        this.bemImovels = bemImovels;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		SituacaoLegalCartorial other = (SituacaoLegalCartorial) obj;
		if (codSituacaoLegalCartorial == null) {
			if (other.codSituacaoLegalCartorial != null)
				return false;
		} else if (!codSituacaoLegalCartorial
				.equals(other.codSituacaoLegalCartorial))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codSituacaoLegalCartorial == null) ? 0
						: codSituacaoLegalCartorial.hashCode());
		return result;
	}
}
