package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * Tabelionato generated by hbm2java
 */
public class Tabelionato implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -6886028897007230859L;
	private Integer codTabelionato;
    private String descricao;
    private String cep;
    private String uf;
    private String municipio;
    private String logradouro;
    private String numero;
    private String bairro;
    private String complemento;
    private String nomeContato;
    private Integer telDdd;
    private String telNumero;
    private Integer codMunicipio;
   
	private Set<BemImovel> bemImovels = new HashSet<BemImovel>(0);

    public Tabelionato() {
    }

    public Tabelionato(Integer codTabelionato, String descricao, String uf,
        String municipio) {
        this.codTabelionato = codTabelionato;
        this.descricao = descricao;
        this.uf = uf;
        this.municipio = municipio;
    }

    public Tabelionato(Integer codTabelionato, String descricao, String cep,
        String uf, String municipio, String logradouro, String numero,
        String bairro, String complemento, Set<BemImovel> bemImovels) {
        this.codTabelionato = codTabelionato;
        this.descricao = descricao;
        this.cep = cep;
        this.uf = uf;
        this.municipio = municipio;
        this.logradouro = logradouro;
        this.numero = numero;
        this.bairro = bairro;
        this.complemento = complemento;
        this.bemImovels = bemImovels;
    }

    public Integer getCodTabelionato() {
        return this.codTabelionato;
    }

    public void setCodTabelionato(Integer codTabelionato) {
        this.codTabelionato = codTabelionato;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getCep() {
        return this.cep;
    }

    public void setCep(String cep) {
        this.cep = cep;
    }

    public String getUf() {
        return this.uf;
    }

    public void setUf(String uf) {
        this.uf = uf;
    }

    public String getMunicipio() {
        return this.municipio;
    }

    public void setMunicipio(String municipio) {
        this.municipio = municipio;
    }

    public String getLogradouro() {
        return this.logradouro;
    }

    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }

    public String getNumero() {
        return this.numero;
    }

    public void setNumero(String numero) {
        this.numero = numero;
    }

    public String getBairro() {
        return this.bairro;
    }

    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    public String getComplemento() {
        return this.complemento;
    }

    public void setComplemento(String complemento) {
        this.complemento = complemento;
    }

    public String getNomeContato() {
		return nomeContato;
	}

	public void setNomeContato(String nomeContato) {
		this.nomeContato = nomeContato;
	}

	public Integer getTelDdd() {
		return telDdd;
	}

	public void setTelDdd(Integer telDdd) {
		this.telDdd = telDdd;
	}

	public String getTelNumero() {
		return telNumero;
	}

	public void setTelNumero(String telNumero) {
		this.telNumero = telNumero;
	}

	public Integer getCodMunicipio() {
		return codMunicipio;
	}

	public void setCodMunicipio(Integer codMunicipio) {
		this.codMunicipio = codMunicipio;
	}

	public Set<BemImovel> getBemImovels() {
        return this.bemImovels;
    }

    public void setBemImovels(Set<BemImovel> bemImovels) {
        this.bemImovels = bemImovels;
    }

    
    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Tabelionato other = (Tabelionato) obj;
		if (codTabelionato == null) {
			if (other.codTabelionato != null)
				return false;
		} else if (!codTabelionato.equals(other.codTabelionato))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codTabelionato == null) ? 0 : codTabelionato.hashCode());
		return result;
	}
}
