package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * TipoEdificacao generated by hbm2java
 */
public class TipoEdificacao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = 3282524083152366202L;
	private Integer codTipoEdificacao;
    private String descricao;
    private Set<Edificacao> edificacaos = new HashSet<Edificacao>(0);

    public TipoEdificacao() {
    }

    public TipoEdificacao(Integer codTipoEdificacao, String descricao) {
        this.codTipoEdificacao = codTipoEdificacao;
        this.descricao = descricao;
    }

    public TipoEdificacao(Integer codTipoEdificacao, String descricao,
        Set<Edificacao> edificacaos) {
        this.codTipoEdificacao = codTipoEdificacao;
        this.descricao = descricao;
        this.edificacaos = edificacaos;
    }

    public Integer getCodTipoEdificacao() {
        return this.codTipoEdificacao;
    }

    public void setCodTipoEdificacao(Integer codTipoEdificacao) {
        this.codTipoEdificacao = codTipoEdificacao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<Edificacao> getEdificacaos() {
        return this.edificacaos;
    }

    public void setEdificacaos(Set<Edificacao> edificacaos) {
        this.edificacaos = edificacaos;
    }

   

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TipoEdificacao other = (TipoEdificacao) obj;
		if (codTipoEdificacao == null) {
			if (other.codTipoEdificacao != null)
				return false;
		} else if (!codTipoEdificacao.equals(other.codTipoEdificacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codTipoEdificacao == null) ? 0 : codTipoEdificacao
						.hashCode());
		return result;
	}
}
