package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * TipoDocumentacao generated by hbm2java
 */
public class TipoDocumentacao implements java.io.Serializable {
  
	private static final long serialVersionUID = -6448827697663741838L;
	private Integer codTipoDocumentacao;
    private String descricao;
    private Set<Documentacao> documentacaos = new HashSet<Documentacao>(0);

    public TipoDocumentacao() {
    }

    public TipoDocumentacao(Integer codTipoDocumentacao, String descricao) {
        this.codTipoDocumentacao = codTipoDocumentacao;
        this.descricao = descricao;
    }

    public TipoDocumentacao(Integer codTipoDocumentacao, String descricao,
        Set<Documentacao> documentacaos) {
        this.codTipoDocumentacao = codTipoDocumentacao;
        this.descricao = descricao;
        this.documentacaos = documentacaos;
    }

    public Integer getCodTipoDocumentacao() {
        return this.codTipoDocumentacao;
    }

    public void setCodTipoDocumentacao(Integer codTipoDocumentacao) {
        this.codTipoDocumentacao = codTipoDocumentacao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<Documentacao> getDocumentacaos() {
        return this.documentacaos;
    }

    public void setDocumentacaos(Set<Documentacao> documentacaos) {
        this.documentacaos = documentacaos;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TipoDocumentacao other = (TipoDocumentacao) obj;
		if (codTipoDocumentacao == null) {
			if (other.codTipoDocumentacao != null)
				return false;
		} else if (!codTipoDocumentacao.equals(other.codTipoDocumentacao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codTipoDocumentacao == null) ? 0 : codTipoDocumentacao
						.hashCode());
		return result;
	}
}
