package gov.pr.celepar.abi.pojo;

import java.util.HashSet;
import java.util.Set;


/**
 * TipoConstrucao generated by hbm2java
 */
public class TipoConstrucao implements java.io.Serializable {
    /**
	 * 
	 */
	private static final long serialVersionUID = -6577940784782522917L;
	private Integer codTipoConstrucao;
    private String descricao;
    private Set<Edificacao> edificacaos = new HashSet<Edificacao>(0);

    public TipoConstrucao() {
    }

    public TipoConstrucao(Integer codTipoConstrucao, String descricao) {
        this.codTipoConstrucao = codTipoConstrucao;
        this.descricao = descricao;
    }

    public TipoConstrucao(Integer codTipoConstrucao, String descricao,
        Set<Edificacao> edificacaos) {
        this.codTipoConstrucao = codTipoConstrucao;
        this.descricao = descricao;
        this.edificacaos = edificacaos;
    }

    public Integer getCodTipoConstrucao() {
        return this.codTipoConstrucao;
    }

    public void setCodTipoConstrucao(Integer codTipoConstrucao) {
        this.codTipoConstrucao = codTipoConstrucao;
    }

    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Set<Edificacao> getEdificacaos() {
        return this.edificacaos;
    }

    public void setEdificacaos(Set<Edificacao> edificacaos) {
        this.edificacaos = edificacaos;
    }

    

    @Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		TipoConstrucao other = (TipoConstrucao) obj;
		if (codTipoConstrucao == null) {
			if (other.codTipoConstrucao != null)
				return false;
		} else if (!codTipoConstrucao.equals(other.codTipoConstrucao))
			return false;
		return true;
	}

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime
				* result
				+ ((codTipoConstrucao == null) ? 0 : codTipoConstrucao
						.hashCode());
		return result;
	}
}
