package gov.pr.celepar.abi.pojo;

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Transient;


/**
 * Usuario generated by hbm2java
 */
public class Usuario implements java.io.Serializable {
	private static final long serialVersionUID = 619176170840065097L;
	
	private Integer codUsuario;
    private String nome;
    private Long idSentinela;
    private Integer situacao;
    private String cpf;
    private String loginSistema;
    private String mail;
    private Date tsInclusao;
    private String cpfResponsavelInclusao;
    private Date tsAtualizacao;
    private String cpfResponsavelAlteracao;
    private Date tsExclusao;
    private String cpfResponsavelExclusao;
    private Instituicao instituicao;
    
	private Set<UsuarioOrgao> listaUsuarioOrgao = new HashSet<UsuarioOrgao>(0);
	private Set<UsuarioGrupoSentinela> listaUsuarioGrupoSentinela = new HashSet<UsuarioGrupoSentinela>(0);

	
    public Usuario() {
    }

    public Usuario(Integer codUsuario) {
        this.codUsuario = codUsuario;
    }

	public Integer getCodUsuario() {
		return codUsuario;
	}

	public void setCodUsuario(Integer codUsuario) {
		this.codUsuario = codUsuario;
	}

	public String getNome() {
		return nome;
	}

	public void setNome(String nome) {
		this.nome = nome;
	}

	public String getCpf() {
		return cpf;
	}

	public void setCpf(String cpf) {
		this.cpf = cpf;
	}

	public String getLoginSistema() {
		return loginSistema;
	}

	public void setLoginSistema(String login) {
		this.loginSistema = login;
	}

	public Long getIdSentinela() {
		return idSentinela;
	}

	public void setIdSentinela(Long idSentinela) {
		this.idSentinela = idSentinela;
	}

	public Integer getSituacao() {
		return situacao;
	}

	public void setSituacao(Integer situacao) {
		this.situacao = situacao;
	}

	public String getMail() {
		return mail;
	}

	public void setMail(String mail) {
		this.mail = mail;
	}

	public Date getTsInclusao() {
		return tsInclusao;
	}

	public void setTsInclusao(Date tsInclusao) {
		this.tsInclusao = tsInclusao;
	}

	public String getCpfResponsavelInclusao() {
		return cpfResponsavelInclusao;
	}

	public void setCpfResponsavelInclusao(String cpfResponsavelInclusao) {
		this.cpfResponsavelInclusao = cpfResponsavelInclusao;
	}

	public Date getTsAtualizacao() {
		return tsAtualizacao;
	}

	public void setTsAtualizacao(Date tsAtualizacao) {
		this.tsAtualizacao = tsAtualizacao;
	}

	public String getCpfResponsavelAlteracao() {
		return cpfResponsavelAlteracao;
	}

	public void setCpfResponsavelAlteracao(String cpfResponsavelAlteracao) {
		this.cpfResponsavelAlteracao = cpfResponsavelAlteracao;
	}

	public Date getTsExclusao() {
		return tsExclusao;
	}

	public void setTsExclusao(Date tsExclusao) {
		this.tsExclusao = tsExclusao;
	}

	public String getCpfResponsavelExclusao() {
		return cpfResponsavelExclusao;
	}

	public void setCpfResponsavelExclusao(String cpfResponsavelExclusao) {
		this.cpfResponsavelExclusao = cpfResponsavelExclusao;
	}

	public Set<UsuarioOrgao> getListaUsuarioOrgao() {
		return listaUsuarioOrgao;
	}

	public void setListaUsuarioOrgao(Set<UsuarioOrgao> listaUsuarioOrgao) {
		this.listaUsuarioOrgao = listaUsuarioOrgao;
	}

	public void setListaUsuarioGrupoSentinela(Set<UsuarioGrupoSentinela> listaUsuarioGrupoSentinela) {
		this.listaUsuarioGrupoSentinela = listaUsuarioGrupoSentinela;
	}

	public Set<UsuarioGrupoSentinela> getListaUsuarioGrupoSentinela() {
		return listaUsuarioGrupoSentinela;
	}
    
    @Transient
    public String getSituacaoDescricao(){
    	String ret = "";
    	if (this.getSituacao() == null){
    		ret = " - "; 
    	}
    	if (this.getSituacao().equals(Integer.valueOf(1))){
    		ret = "Ativo"; 
    	}
    	if (this.getSituacao().equals(Integer.valueOf(0))){
    		ret = "Inativo"; 
    	}
    	return ret;
    }

   

	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result
				+ ((codUsuario == null) ? 0 : codUsuario.hashCode());
		return result;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Usuario other = (Usuario) obj;
		if (codUsuario == null) {
			if (other.codUsuario != null)
				return false;
		} else if (!codUsuario.equals(other.codUsuario))
			return false;
		return true;
	}

	public Instituicao getInstituicao() {
		return instituicao;
	}

	public void setInstituicao(Instituicao instituicao) {
		this.instituicao = instituicao;
	}
    

}
