package gov.pr.celepar.ucs_manterinstituicao.pojo;

// Generated 23/06/2015 11:12:09 by Hibernate Tools 3.2.0.CR1
import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.ManyToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;


/**
 * AreaInteresse generated by hbm2java
 */
@Entity
@Table(name = "tb_area_interesse", schema = "public")
public class AreaInteresse implements java.io.Serializable {
	private static final long serialVersionUID = -2465900626677872348L;
	private Integer codAreaInteresse;
    private String descricao;
    private Set<Instituicao> instituicaos = new HashSet<Instituicao>(0);

    public AreaInteresse() {
    }

    public AreaInteresse(Integer codAreaInteresse, String descricao) {
        this.codAreaInteresse = codAreaInteresse;
        this.descricao = descricao;
    }

    public AreaInteresse(Integer codAreaInteresse, String descricao,
        Set<Instituicao> instituicaos) {
        this.codAreaInteresse = codAreaInteresse;
        this.descricao = descricao;
        this.instituicaos = instituicaos;
    }

    @Id
    @SequenceGenerator(name="AREA_ID_SEQ", sequenceName="tb_area_interesse_cod_area_interesse_seq")
    @GeneratedValue(strategy=GenerationType.AUTO, generator="AREA_ID_SEQ")
    @Column(name = "cod_area_interesse", nullable = false)
    public Integer getCodAreaInteresse() {
        return this.codAreaInteresse;
    }

    public void setCodAreaInteresse(Integer codAreaInteresse) {
        this.codAreaInteresse = codAreaInteresse;
    }

    @Column(name = "descricao", nullable = false, length = 80)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    @ManyToMany(fetch = FetchType.LAZY, mappedBy = "areaInteresses")
    public Set<Instituicao> getInstituicaos() {
        return this.instituicaos;
    }

    public void setInstituicaos(Set<Instituicao> instituicaos) {
        this.instituicaos = instituicaos;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof AreaInteresse)) {
            return false;
        }

        AreaInteresse castOther = (AreaInteresse) other;

        return ((this.getCodAreaInteresse() == castOther.getCodAreaInteresse()) ||
        ((this.getCodAreaInteresse() != null) &&
        (castOther.getCodAreaInteresse() != null) &&
        this.getCodAreaInteresse().equals(castOther.getCodAreaInteresse())));
    }

    public int hashCode() {
        int result = 17;

        result = (37 * result) +
            ((getCodAreaInteresse() == null) ? 0
                                             : this.getCodAreaInteresse()
                                                   .hashCode());

        return result;
    }
}
