package gov.pr.celepar.ucs_manterinstituicao.pojo;

// Generated 07/07/2015 15:18:06 by Hibernate Tools 3.2.0.CR1
import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;


/**
 * Colaborador generated by hbm2java
 */
@Entity
@Table(name = "tb_colaborador", schema = "public")
public class Colaborador implements java.io.Serializable {
	private static final long serialVersionUID = 3641471406820863519L;
	private Integer idColaborador;
    private Instituicao instituicao;
    private String cpf;
    private String rg;
    private String nome;
    private String email;
    private Date dataNascimento;
    private Date dataAdmissao;
    private Boolean indSexo;
    private Date dataDEmissao;
    private String celular;
    private String telefone;
    
    @Column(name = "celular", length = 20)
    public String getCelular() {
		return celular;
	}

	public void setCelular(String celular) {
		this.celular = celular;
	}

	@Column(name = "telefone", length = 20)
	public String getTelefone() {
		return telefone;
	}

	public void setTelefone(String telefone) {
		this.telefone = telefone;
	}

	public static long getSerialversionuid() {
		return serialVersionUID;
	}

	public Colaborador() {
    }

    public Colaborador(Integer idColaborador, Instituicao instituicao,
        String cpf, String rg, String nome, String email, Date dataNascimento,
        Date dataAdmissao, String telefone, String celular) {
        this.idColaborador = idColaborador;
        this.instituicao = instituicao;
        this.cpf = cpf;
        this.rg = rg;
        this.nome = nome;
        this.email = email;
        this.dataNascimento = dataNascimento;
        this.dataAdmissao = dataAdmissao;
        this.celular = celular;
        this.telefone = telefone;
    }

    public Colaborador(Integer idColaborador, Instituicao instituicao,
        String cpf, String rg, String nome, String email, Date dataNascimento,
        Date dataAdmissao, Boolean indSexo, Date dataDEmissao) {
        this.idColaborador = idColaborador;
        this.instituicao = instituicao;
        this.cpf = cpf;
        this.rg = rg;
        this.nome = nome;
        this.email = email;
        this.dataNascimento = dataNascimento;
        this.dataAdmissao = dataAdmissao;
        this.indSexo = indSexo;
        this.dataDEmissao = dataDEmissao;
    }

    @Id
    @SequenceGenerator(name="COLABORADOR_ID_SEQ", sequenceName="tb_colaborador_id_colaborador_seq")
    @GeneratedValue(strategy=GenerationType.AUTO, generator="COLABORADOR_ID_SEQ")
    @Column(name = "id_colaborador", nullable = false)
    public Integer getIdColaborador() {
        return this.idColaborador;
    }

    public void setIdColaborador(Integer idColaborador) {
        this.idColaborador = idColaborador;
    }

    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "cod_instituicao", nullable = false)
    public Instituicao getInstituicao() {
        return this.instituicao;
    }

    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }

    @Column(name = "cpf", nullable = false, length = 11)
    public String getCpf() {
        return this.cpf;
    }

    public void setCpf(String cpf) {
        this.cpf = cpf;
    }

    @Column(name = "rg", nullable = false, length = 20)
    public String getRg() {
        return this.rg;
    }

    public void setRg(String rg) {
        this.rg = rg;
    }

    @Column(name = "nome", nullable = false, length = 150)
    public String getNome() {
        return this.nome;
    }

    public void setNome(String nome) {
        this.nome = nome;
    }

    @Column(name = "email", nullable = false, length = 150)
    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_nascimento", nullable = false, length = 8)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }

    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_admissao", nullable = false, length = 8)
    public Date getDataAdmissao() {
        return this.dataAdmissao;
    }

    public void setDataAdmissao(Date dataAdmissao) {
        this.dataAdmissao = dataAdmissao;
    }

    @Column(name = "ind_sexo")
    public Boolean getIndSexo() {
        return this.indSexo;
    }

    public void setIndSexo(Boolean indSexo) {
        this.indSexo = indSexo;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name = "data_demissao", length = 8)
    public Date getDataDEmissao() {
        return this.dataDEmissao;
    }

    public void setDataDEmissao(Date dataDEmissao) {
        this.dataDEmissao = dataDEmissao;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof Colaborador)) {
            return false;
        }

        Colaborador castOther = (Colaborador) other;

        return ((this.getIdColaborador() == castOther.getIdColaborador()) ||
        ((this.getIdColaborador() != null) &&
        (castOther.getIdColaborador() != null) &&
        this.getIdColaborador().equals(castOther.getIdColaborador())));
    }

    public int hashCode() {
        int result = 17;

        result = (37 * result) +
            ((getIdColaborador() == null) ? 0 : this.getIdColaborador()
                                                    .hashCode());

        return result;
    }
}
