package gov.pr.celepar.ucs_manterinstituicao.pojo;

// Generated 23/06/2015 11:12:09 by Hibernate Tools 3.2.0.CR1
import gov.pr.celepar.ucs_manterinstituicao.decorator.NaturezaJuridicaDecorator;

import java.util.HashSet;
import java.util.Set;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Transient;


/**
 * NaturezaJuridica generated by hbm2java
 */
@Entity
@Table(name = "tb_natureza_juridica", schema = "public")
public class NaturezaJuridica implements java.io.Serializable {
	private static final long serialVersionUID = 2912986067162349518L;
	private Integer codNaturezaJuridica;
    private String descricao;
    private Set<Instituicao> instituicaos = new HashSet<Instituicao>(0);

    public NaturezaJuridica() {
    }

    public NaturezaJuridica(Integer codNaturezaJuridica, String descricao) {
        this.codNaturezaJuridica = codNaturezaJuridica;
        this.descricao = descricao;
    }

    public NaturezaJuridica(Integer codNaturezaJuridica, String descricao,
        Set<Instituicao> instituicaos) {
        this.codNaturezaJuridica = codNaturezaJuridica;
        this.descricao = descricao;
        this.instituicaos = instituicaos;
    }

    @Id
    @Column(name = "cod_natureza_juridica", nullable = false)
    public Integer getCodNaturezaJuridica() {
        return this.codNaturezaJuridica;
    }

    public void setCodNaturezaJuridica(Integer codNaturezaJuridica) {
        this.codNaturezaJuridica = codNaturezaJuridica;
    }

    @Column(name = "descricao", nullable = false, length = 80)
    public String getDescricao() {
        return this.descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }
    
    @Transient
    public String getMascara() throws Exception{
    	return new NaturezaJuridicaDecorator().decorate(this);
     }
    
    @OneToMany(fetch = FetchType.LAZY, mappedBy = "naturezaJuridica")
    public Set<Instituicao> getInstituicaos() {
        return this.instituicaos;
    }

    public void setInstituicaos(Set<Instituicao> instituicaos) {
        this.instituicaos = instituicaos;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof NaturezaJuridica)) {
            return false;
        }

        NaturezaJuridica castOther = (NaturezaJuridica) other;

        return ((this.getCodNaturezaJuridica() == castOther.getCodNaturezaJuridica()) ||
        ((this.getCodNaturezaJuridica() != null) &&
        (castOther.getCodNaturezaJuridica() != null) &&
        this.getCodNaturezaJuridica().equals(castOther.getCodNaturezaJuridica())));
    }

    public int hashCode() {
        int result = 17;

        result = (37 * result) +
            ((getCodNaturezaJuridica() == null) ? 0
                                                : this.getCodNaturezaJuridica()
                                                      .hashCode());

        return result;
    }
}
