package gov.pr.celepar.ucs_manterinstituicao.pojo;

// Generated 23/06/2015 11:12:09 by Hibernate Tools 3.2.0.CR1
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import org.apache.commons.lang.builder.EqualsBuilder;


/**
 * InstituicaoTelefone generated by hbm2java
 */
@Entity
@Table(name = "tb_instituicao_telefone", schema = "public")
public class Telefone implements java.io.Serializable {
	private static final long serialVersionUID = -7962755104669699862L;
	
	private Integer codInstituicaoTelefone;
    private Instituicao instituicao;
    private String telefone;

    public Telefone() {
    }

    public Telefone(Integer codInstituicaoTelefone,
        Instituicao instituicao, String telefone) {
        this.codInstituicaoTelefone = codInstituicaoTelefone;
        this.instituicao = instituicao;
        this.telefone = telefone;
    }

    @Id
    @SequenceGenerator(name="TELEFONE_ID_SEQ", sequenceName="tb_instituicao_telefone_cod_instituicao_telefone_seq")
    @GeneratedValue(strategy=GenerationType.AUTO, generator="TELEFONE_ID_SEQ")
    @Column(name = "cod_instituicao_telefone", nullable = false)
    public Integer getCodInstituicaoTelefone() {
        return this.codInstituicaoTelefone;
    }

    public void setCodInstituicaoTelefone(Integer codInstituicaoTelefone) {
        this.codInstituicaoTelefone = codInstituicaoTelefone;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "cod_instituicao", nullable = false)
    public Instituicao getInstituicao() {
        return this.instituicao;
    }

    public void setInstituicao(Instituicao instituicao) {
        this.instituicao = instituicao;
    }

    @Column(name = "telefone", nullable = false, length = 20)
    public String getTelefone() {
        return this.telefone;
    }

    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    public boolean equals(Object other) {
        if ((this == other)) {
            return true;
        }

        if ((other == null)) {
            return false;
        }

        if (!(other instanceof Telefone)) {
            return false;
        }

        Telefone castOther = (Telefone) other;
        
        System.out.println(this.getTelefone());
        System.out.println(castOther.getTelefone());
        
        return new EqualsBuilder().append(this.getTelefone(), castOther.getTelefone()).isEquals();
    }

    public int hashCode() {
        int result = 17;

        result = (37 * result) +
            ((getCodInstituicaoTelefone() == null) ? 0
                                                   : this.getCodInstituicaoTelefone()
                                                         .hashCode());

        return result;
    }
}
